- name: Initial setup of pfsense
  hosts: pfsense
  vars_files:
    - "../../../group_vars/homelab.yml"
    - "../../../vault/proxmox_vault.yml"
  ignore_errors: false
  tasks:
    - name: Setup existing admin user with SSH
      pfsensible.core.pfsense_user:
        authorizedkeys: "{{ ssh_pub_key_file }}"
        name: "admin"
        groups:
          - "admins"
        priv: ["page-all", "user-shell-access"]
        scope: "system"
        state: "present"

    - name: Setup LAN interface
      pfsensible.core.pfsense_interface:
        blockbogons: false
        blockpriv: false
        enable: true
        descr: "LAN"
        interface: "vtnet1"
        ipv4_type: "static"
        ipv4_address: "192.168.2.254"
        ipv4_prefixlen: 24
        state: "present"
