- name: 
  hosts: pfsense
  tasks:
    - name: ping
      ansible.builtin.ping:
    - name: Test pfsensible core
      pfsensible.core.pfsense_interface:
        blockbogons: false
        blockpriv: false
        enable: true
        descr: "LAN"
        interface: "vtnet1"
        ipv4_address: "192.168.2.1"
        ipv4_prefixlen: 24
        ipv4_type: "static"
        state: "present"
